name: team_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-178.1.beta <3.0.0"

dependencies:
  firebase_core:
  firebase_auth:
  firebase_storage:
  firebase_analytics:
  cloud_firestore:
  provider:
  google_sign_in:
  http:
  location:
  google_maps_flutter:
  geolocator:
  url_launcher:
  custom_radio_grouped_button: any

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/chat.png
    - assets/icon.png
    - assets/appicon.png
    - assets/chatroom.png
    - assets/search.png
    - assets/logo.png
    - assets/wait.png

  uses-material-design: true